name: Delete Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 2
        keep_minimum_runs: 0

    - name: Remove old Releases
      uses: Vucko130/delete-older-releases@v0.2.1
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        repo: ${{ github.repository }}
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
